version: '3'

services:
  api:
    build:
      context: .
      args:
        - GITHUBKEY
    environment:
      POSTGRES_HOST: db
    env_file:
      - db.env
    networks:
      - sweetrpg
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres
    env_file:
      - db.env
    networks:
      - sweetrpg
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    restart: unless-stopped

networks:
  sweetrpg:

volumes:
  dbdata:
