---
apiVersion: v1
kind: Namespace
metadata:
  name: sweetrpg

---
apiVersion: v1
data:
  POSTGRES_DB: Z2FtZXN5c3RlbQo=
  POSTGRES_PASSWORD: cGFzc3dvcmQK
  POSTGRES_USER: c3dlZXRycGcK
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sweetrpg-gamesystem-api-secret
  name: sweetrpg-gamesystem-api-secret
  namespace: sweetrpg

---
apiVersion: v1
data:
  POSTGRES_DB: Z2FtZXN5c3RlbQo=
  POSTGRES_PASSWORD: cGFzc3dvcmQK
  POSTGRES_USER: c3dlZXRycGcK
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sweetrpg-gamesystem-db-secret
  name: sweetrpg-gamesystem-db-secret
  namespace: sweetrpg

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dbdata
  name: sweetrpg-gamesystem-db-data
  namespace: sweetrpg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: sweetrpg-gamesystem-db
  namespace: sweetrpg
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: sweetrpg-gamesystem-db-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: sweetrpg-gamesystem-db-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: sweetrpg-gamesystem-db-secret
        image: postgres
        name: sweetrpg-gamesystem-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
      restartPolicy: Always
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: sweetrpg-gamesystem-db-data
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: sweetrpg-gamesystem-api
  namespace: sweetrpg
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: sweetrpg-gamesystem-api-secret
        - name: POSTGRES_HOST
          value: sweetrpg-gamesystem-db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: sweetrpg-gamesystem-api-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: sweetrpg-gamesystem-api-secret
        image: localhost:5555/sweetrpg/gamesystem-api:latest
        name: sweetrpg-gamesystem-api
        resources: {}
      restartPolicy: Always
status: {}
